# Usa un'immagine di base con PHP, Apache e supporto per MySQL
FROM php:7.4-apache-buster

# Aggiorna il sistema operativo e installa i pacchetti necessari
RUN apt-get update && apt-get install -y \
    mariadb-client \
    libpng-dev \
    libjpeg-dev \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-configure gd --with-jpeg=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd mysqli pdo_mysql zip

# Abilita il modulo Apache per il rewrite
RUN a2enmod rewrite

# Copia i file del sito nella directory del web server
COPY cv/ /var/www/html/

# Copia la configurazione di Apache per il sito
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Copia la configurazione di PHP
COPY php.ini /usr/local/etc/php/conf.d/php.ini

# Copia la configurazione di PhpMyAdmin
COPY phpmyadmin-config.inc.php /usr/share/phpmyadmin/config.inc.php

# Imposta la variabile d'ambiente per l'host del database
ENV MYSQL_HOST=localhost

# Imposta la variabile d'ambiente per la porta del database
ENV MYSQL_PORT=3306

# Imposta la variabile d'ambiente per il nome del database
ENV MYSQL_DATABASE=finsoft

# Imposta la variabile d'ambiente per il nome utente del database
ENV MYSQL_USER=finsoft

# Imposta la variabile d'ambiente per la password del database
ENV MYSQL_PASSWORD=finsoft

# Esponi la porta 80 per il traffico HTTP
EXPOSE 80

# Avvia il server web Apache
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]



FROM php:7.4-apache

# Update system core
#RUN apt update -y && apt install nano net-tools telnet -y && apt upgrade -y
#RUN docker-php-ext-install pdo pdo_mysql bcmath && docker-php-ext-enable pdo pdo_mysql bcmath 
RUN a2enmod authz_groupfile rewrite

CMD chmod -R 777 /var/www/html/ && \
    chown www-data:www-data /var/www/html/ -R && \
    /etc/init.d/apache2 restart && \
    tail -F /var/log/apache2/access.log