version: "3.9"

services:
  spring:
    image: spring:1.0
    ports:
      - "8080:8080"
    networks:
      - netspring

  mariabiblio:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: finsoft
    networks:
      - netspring

networks:
  netspring:
    external: true