version: "3.9"

services:
  springdocker:
    image: matteo29mar/spring:2.1
    
    ports:
      - "8080:8080"
    networks:
      - netspring
    depends_on:
      - db-container
  db-container:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: finsoft
      MYSQL_DATABASE: maria
    volumes:
      - my-mariadb:/var/lib/mysql
    networks:
      - netspring
volumes:
  my-mariadb:
networks:
  netspring: